[package]
name = "appkit-bindings"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_os = "macos")'.build-dependencies]
bindgen = "0.59"

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2"